color: null
fieldLayouts:
  c8f2dace-251c-4a6a-8a6d-48725d1c3d6a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-04T00:53:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 84acb25d-b818-4988-a724-9dc53c6a6d83
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5519b1b4-2a13-4f73-aa4e-eb94077dc65e
        userCondition: null
handle: basic
hasTitleField: true
icon: user-cowboy
name: Basic
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
