color: null
fieldLayouts:
  06d7ffb8-d7cb-41fa-a5a1-d2cc1571ea5c:
    cardView:
      - 'layoutElement:27fb0713-977f-4525-a4ba-f3bf29675b1f'
      - 'layoutElement:3dccf67a-182f-4fc7-b5a4-a8f577b03a30'
      - 'layoutElement:9c6aac23-7b99-4070-91a2-d096ef5512da'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-22T23:43:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d248d9e1-2ec7-4773-a62e-c4b8eec01755
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T23:43:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e08f579c-0df8-4333-b155-fc9bb9f623a6 # Simple Text Editor
            handle: subTitle
            includeInCards: true
            instructions: null
            label: 'Sub Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dccf67a-182f-4fc7-b5a4-a8f577b03a30
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T23:43:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a512079-228e-4c63-b2b4-c1e1860c8b54 # Image
            handle: background
            includeInCards: true
            instructions: null
            label: Background
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c6aac23-7b99-4070-91a2-d096ef5512da
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-22T23:43:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 546fae56-25d8-4cd4-8696-20f2782b3881 # Single Line Text
            handle: columns
            includeInCards: true
            instructions: null
            label: Columns
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27fb0713-977f-4525-a4ba-f3bf29675b1f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-22T23:43:24+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 66ae5d83-1293-46a7-bf32-356e9c32f0f9
            userCondition: null
          -
            dateAdded: '2025-04-22T23:43:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 84792880-ee67-488c-b382-e2894d76fd72 # Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 119d19dd-6575-4941-a16d-c0b119f10752
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 33ece980-16ea-4f4d-8ed8-2e58f6735ad2
        userCondition: null
handle: cards
hasTitleField: true
icon: null
name: Cards
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
