color: null
fieldLayouts:
  5c118e50-b893-45c9-9fa4-c24cf4dd16e7:
    cardView:
      - 'layoutElement:ef6b62c8-52f8-4ec0-8caa-d3cbd35c507a'
      - 'layoutElement:eea83ee7-4e7e-432c-8584-f82ba2966b40'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-22T23:39:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d94301f2-85d7-46ec-917a-5c54d9834e10
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T23:41:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a512079-228e-4c63-b2b4-c1e1860c8b54 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef6b62c8-52f8-4ec0-8caa-d3cbd35c507a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T23:41:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e08f579c-0df8-4333-b155-fc9bb9f623a6 # Simple Text Editor
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eea83ee7-4e7e-432c-8584-f82ba2966b40
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T23:41:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a36687c0-47fa-46ad-8c43-47079d855003 # Link Field
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 779f6f69-608a-46d3-acfe-3d0e5a05bf18
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f2da4bd6-6b33-4673-81f6-bf50c94cad9a
        userCondition: null
handle: card
hasTitleField: true
icon: null
name: Card
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
