color: null
fieldLayouts:
  cb202651-e40c-4a08-a7bd-2e02a69f54c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-03T05:11:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b17f84d6-50dd-49c2-b5da-8d1bf4a054d2
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-03T05:13:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ad87c9e5-9aab-40ff-ba76-ea12af7231b4 # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 954c875a-21f0-4e4b-90ea-5b6dbf6ff5bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-03T05:13:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 61c8a866-9126-4d78-b3f1-19668b554bc8 # Phone number 
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc19409a-196c-4059-a467-12d4522c9d1c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-03T05:13:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 72837d69-c9e7-4272-b0b4-f5b576af9837 # Notes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e942a57-bd8e-463b-8708-18a8e73202b6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-04T23:56:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 38c6528b-4dc2-4371-8d94-19b13f8c4a1c # customer name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d19e4212-3558-43ea-9ddc-43d5a945769a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-04T23:56:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6a01f02e-4819-48d0-98c4-28382ab0278f # vehicles(linked)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b68c776b-69cc-4d1f-b2e6-31d014806a69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d747bea-b74f-4e03-a122-3aab0786ced9
        userCondition: null
handle: customer
hasTitleField: true
icon: person
name: Customer
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
