color: null
fieldLayouts:
  742f7c1a-4d6e-4e9a-9446-4c550aba81e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-08T00:15:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 575ff463-3a99-4cb2-b75d-d42dec6c8bba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-08T00:16:36+00:00'
            elementCondition: null
            fieldUid: 0a512079-228e-4c63-b2b4-c1e1860c8b54 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baee4dfd-aac1-420c-ab65-c162a9b1af75
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-08T00:16:36+00:00'
            elementCondition: null
            fieldUid: 2eb0dc5e-9a77-4ac7-9ca8-c933c11d65bc # Full Options Editor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d59d7ea-0c57-448a-9389-0de5ea0420f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08f44fd5-24f8-4db6-a7e8-4dd3a372e8bc
        userCondition: null
handle: home
hasTitleField: true
icon: ''
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
