color: null
fieldLayouts:
  da49e34d-4488-470a-b429-3807b94f94d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-03T02:44:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 74684534-8011-4515-a3a6-46c50a47fdd2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: googleMapsApi
            includeInCards: false
            instructions: null
            label: 'Google Maps Api'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbfa196d-8d17-4064-a63b-e703c262c923
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: googleAnalytics
            includeInCards: false
            instructions: null
            label: 'Google Analytics'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c016ccd-f324-474c-964e-57097e297979
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: gtm
            includeInCards: false
            instructions: null
            label: 'Google Tag Manager'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f2dff3c-d140-4c04-99c8-611e54ce4c3b
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: clarity
            includeInCards: false
            instructions: null
            label: 'Clarity Code'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48895358-f22c-4d6f-ad4a-a048cfd8a4da
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5f72ffb3-1925-4529-a54f-02b8cbcbd02e
            userCondition: null
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: 53449f53-916a-460c-84ed-4c4342067e0d
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4380c5d-f3b9-41de-aa26-b2016e45f22e
            userCondition: null
            warning: null
            width: 100
        name: 'Site Info'
        uid: 4297a4e1-48fe-45d0-ac9c-870b370e3836
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: phoneNumber
            includeInCards: false
            instructions: null
            label: 'Phone Number'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a39ce45-5160-451a-aece-0652ba8208b6
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: phoneNumber2
            includeInCards: false
            instructions: null
            label: 'Phone Number'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c158b664-b98b-455b-a2f1-0efd9f1d9590
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d388c229-d406-4b40-930e-6c6a14eb67cb
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa529e71-3082-46d5-a2c8-71dcc40dcbbe
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0b3e9240-7145-46ad-9dc4-b27bbcb5b027
            userCondition: null
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: address
            includeInCards: false
            instructions: null
            label: Address
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1124ed4-3339-43af-b4ab-63318891ec8a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: lat
            includeInCards: false
            instructions: null
            label: Latitude
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5575e1a-59c5-401b-8629-6bcd6581c16a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: d09e7eaa-db8d-4b8c-a242-4cad3af936c0
            handle: lng
            includeInCards: false
            instructions: null
            label: Longitude
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5842d58-3593-4229-998f-1e6f5bea44ca
            userCondition: null
            warning: null
            width: 50
        name: 'Contact Info'
        uid: b2bf5e38-8b62-475c-8de1-e42aca093e85
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-03T02:44:59+00:00'
            elementCondition: null
            fieldUid: 1b2b5d25-f3c7-4710-970c-bf4dd3ce9bc9
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a899c6e-116d-4f60-a2d0-48791c2cf1ce
            userCondition: null
            warning: null
            width: 100
        name: 'Social Media'
        uid: f7590f5d-3c05-467b-9c01-cb274ba2ba8a
        userCondition: null
handle: siteSettings
hasTitleField: false
icon: gear
name: 'Site Settings'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Site Settings'
titleTranslationKeyFormat: null
titleTranslationMethod: site
