color: null
fieldLayouts:
  348376bd-3fe2-4a19-98a2-bed85ff8f459:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-07T23:46:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 57753152-2b37-48c8-bc53-04bb9ce2f91f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eac94357-5fb1-4d7f-aa58-28a02b2ccac3
        userCondition: null
handle: testmatrix
hasTitleField: true
icon: null
name: TestMatrix
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
