color: null
fieldLayouts:
  dca5231c-cf7c-4161-a3fc-089486afc543:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-22T23:33:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2eb0dc5e-9a77-4ac7-9ca8-c933c11d65bc # Full Options Editor
            handle: textContent
            includeInCards: false
            instructions: null
            label: 'Text Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6cc39ead-a99a-42ab-abd1-90317a58cce4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f835c826-1199-4847-8912-fc23ce11a12a
        userCondition: null
handle: text
hasTitleField: false
icon: null
name: 'Text Editor'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
