headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Full
options:
  alignment:
    options:
      - left
      - right
      - center
  fontColor:
    colors:
      -
        color: 'hsl(0, 0%, 0%)'
        label: Black
      -
        color: '#D7272E'
        label: 'Main Red'
      -
        color: '#B02028'
        label: 'Secondary Red'
      -
        color: '#F69D8F'
        label: Pink
      -
        color: '#5D7D2A'
        label: Green
      -
        color: '#353635'
        label: Grey
  fontFamily:
    options:
      - 'caveat-brush, sans-serif'
      - 'azo-sans-web, serif'
  fontSize:
    options:
      - '12'
      - '14'
      - default
      - '18'
      - '20'
      - '22'
      - '24'
      - '30'
      - '34'
      - '59'
      - '73'
  image:
    resizeUnit: '%'
    toolbar:
      - toggleImageCaption
      - imageTextAlternative
      - '|'
      - 'imageStyle:inline'
      - 'imageStyle:wrapText'
      - 'imageStyle:breakText'
      - '|'
      - linkImage
      - '|'
      - transformImage
  imageResizeHandles: true
  link:
    addTargetToExternalLinks: true
    decorators:
      -
        attributes:
          class: 'btn leading-loose mr-3 btnDark px-4 inline-flex text-xs uppercase font-bold transition text-white bg-dark3 border-2 border-transparent hover:text-dark3 hover:bg-white hover:border-dark3 standardBtn active'
        label: 'Primary button style'
        mode: manual
      -
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'open in new tab'
        mode: manual
toolbar:
  - sourceEditing
  - heading
  - '|'
  - bold
  - italic
  - link
  - '|'
  - alignment
  - outdent
  - indent
  - '|'
  - underline
  - strikethrough
  - subscript
  - superscript
  - '|'
  - bulletedList
  - numberedList
  - '|'
  - fontSize
  - fontFamily
  - fontColor
  - fontBackgroundColor
  - '|'
  - insertImage
  - mediaEmbed
  - '|'
  - blockQuote
  - insertTable
  - '|'
  - removeFormat
