altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  02687944-950a-4b56-9df5-d696cdbd36ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-23T01:27:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 453a5d01-9afe-4eff-8564-4ba732e72ead
            userCondition: null
            warning: null
            width: 50
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-04-23T01:29:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 8df9cbb8-8fe2-4743-8d5c-c8873496179c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 88ce10b4-9134-43c8-bda8-428a19ab1134
        userCondition: null
fs: image
handle: image
name: Image
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
