columnSuffix: null
handle: bookeingTime
instructions: null
name: 'Bookeing Time'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 10
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
