columnSuffix: null
handle: hero
instructions: null
name: hero
searchable: false
settings:
  createButtonLabel: 'New Hero Slide'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 8dff61be-651f-4492-9ed0-9dd9769582aa # Hero
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
