columnSuffix: null
handle: pageBuilder
instructions: null
name: 'Page Builder'
searchable: false
settings:
  createButtonLabel: 'Add A Block'
  defaultIndexViewMode: table
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - ea2f7c18-13e4-46aa-a8d6-51fddd944c23 # Cards
    -
      __assoc__:
        -
          - uid
          - e1e51f73-bcc5-4d9b-a626-c93dacc23cc0 # Heading
    -
      __assoc__:
        -
          - uid
          - ddca42c6-5eea-4420-b3e0-3f0d332ebe6d # Text Editor
    -
      __assoc__:
        -
          - uid
          - bd6637fe-941e-4091-90a2-b0bf833351f8 # Hero Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
