columnSuffix: null
handle: priority
instructions: 'Optional: Normal, Urgent, VIP.'
name: Priority
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - low
        -
          - value
          - low
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - medium
        -
          - value
          - medium
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - high
        -
          - value
          - high
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - urgent
        -
          - value
          - urgent
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
