defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 546b5180-0a10-4e0f-af11-62d612a9d04b # Bookings
handle: bookings
maxAuthors: 1
name: Bookings
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  929b82bc-c4d7-473f-857c-ea44cc6c8984: # Mechanicbackend Ddev
    enabledByDefault: true
    hasUrls: true
    template: docs
    uriFormat: 'bookings/{slug}'
type: channel
