defaultPlacement: end
enableVersioning: true
entryTypes:
  - fcf95a95-6db1-48dd-9aa8-a641adeec479
handle: error
maxAuthors: 1
name: Errors
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
