defaultPlacement: end
enableVersioning: true
entryTypes:
  - 401590d1-1d18-4503-8baf-2560169e8c8f # Navigation
handle: footerNavigation
maxAuthors: 1
name: 'Footer Navigation'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: e166b4ed-e1a6-4392-a334-278bf1424c0d
type: structure
