defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ca29fc9a-dddc-4670-af50-2071e221c176 # inventory
handle: inventory
maxAuthors: 1
name: Inventory
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  929b82bc-c4d7-473f-857c-ea44cc6c8984: # Mechanicbackend Ddev
    enabledByDefault: true
    hasUrls: true
    template: inventory/_entry.twig
    uriFormat: 'inventory/{slug}'
type: channel
