defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6daa3ceb-95bd-4544-9173-a67cf9d06f59 # Invoices
handle: invoices
maxAuthors: 1
name: Invoices
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  929b82bc-c4d7-473f-857c-ea44cc6c8984: # Mechanicbackend Ddev
    enabledByDefault: true
    hasUrls: true
    template: invoices/_entry.twig
    uriFormat: 'invoices/{slug}'
type: channel
