defaultPlacement: beginning
enableVersioning: true
entryTypes:
  -
    uid: d7083cb8-47c6-4c39-83cf-1c67eac26e85 # Card
handle: products
maxAuthors: 1
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Docs
      -
        - urlFormat
        - 'docs/{slug}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: 045fe461-db0f-4880-896c-c1100a5d8c31
type: structure
