defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fde35a7e-3f98-4a63-89dd-658a215562b3 # Quotation
handle: quotation
maxAuthors: 1
name: Quotation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  929b82bc-c4d7-473f-857c-ea44cc6c8984: # Mechanicbackend Ddev
    enabledByDefault: true
    hasUrls: true
    template: quotation/_entry.twig
    uriFormat: 'quotation/{slug}'
type: channel
