defaultPlacement: end
enableVersioning: true
entryTypes:
  - 05fb432b-77b1-40bc-8ff7-56425ce230ad # Site Settings
handle: siteSettings
maxAuthors: 1
name: 'Site Settings'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
