defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 16b8809b-cf02-47e9-8e2a-f65306335511 # Basic
handle: stores
maxAuthors: 1
name: Stores
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  929b82bc-c4d7-473f-857c-ea44cc6c8984: # Mechanicbackend Ddev
    enabledByDefault: true
    hasUrls: true
    template: docs
    uriFormat: 'stores/{slug}'
structure:
  maxLevels: null
  uid: 9eefd0a5-5a1a-4a07-81f9-4650f1b8fed9
type: structure
